{
  lib,
  pkgs,
  system,
}:

let
  mkTool = pkgs.callPackage ./mk-tool.nix { };

  dataDir = ../data;

  # Generated by `hcnix update`: Nix system double -> Go OS/architecture.
  platforms = builtins.fromJSON (builtins.readFile (dataDir + "/platforms.json"));

  # Generated by `hcnix update`: product -> per-system latest release pointers.
  # Keeping this separate from the per-product manifests means enumerating the
  # tree costs one small parse, and a product's ~450-release manifest is only
  # read when that product is actually evaluated.
  index = builtins.fromJSON (builtins.readFile (dataDir + "/index.json"));

  # Manifests record a nixpkgs license attribute name, resolved per version by
  # the updater (the releases API reports "oss" for BUSL builds too).
  toLicense =
    name:
    lib.licenses.${name}
      or (throw "nix-hashicorp-tools: unknown license attribute '${name}' in manifest");

  mkProduct =
    product:
    let
      entry = index.${product};

      manifest = builtins.fromJSON (builtins.readFile (dataDir + "/products/${product}.json"));

      # Releases with no build for the system currently being evaluated simply
      # do not appear in the tree.
      available = lib.filterAttrs (_: release: release.platforms ? ${system}) manifest.versions;

      target = platforms.${system};

      releases = lib.mapAttrs (
        version: release:
        mkTool {
          inherit (manifest) product mainProgram;
          inherit version;
          inherit (target) os arch;
          sha256 = release.platforms.${system};
          description = manifest.description or "";
          homepage = manifest.homepage or "";
          license = toLicense release.license;
          platforms = builtins.attrNames release.platforms;
        }
      ) available;

      # `manifest.order` is semver-ascending, so this stays meaningfully sorted.
      versions = lib.filter (version: available ? ${version}) manifest.order;

      # The newest release overall need not have a build for every system, so
      # these pointers are resolved per system by the updater.
      pointer =
        name: source: lib.optionalAttrs (source ? ${system}) { ${name} = releases.${source.${system}}; };
    in
    releases
    // {
      inherit versions product;
    }
    // pointer "latest" entry.latest
    // pointer "latestPrerelease" (entry.latestPrerelease or { });

  # A product is only present for systems on which it has at least one release,
  # so consumers can rely on `hashicorp.<product>.latest` existing wherever
  # `hashicorp.<product>` does.
  productNames = builtins.attrNames (lib.filterAttrs (_: entry: entry.latest ? ${system}) index);
in
lib.genAttrs productNames mkProduct
